  int SDM_SPECTRAL_MAX_L = 512;
  int SDM_SPECTRAL_NUM_LEVELS = 5;
  array[5] int SDM_SPECTRAL_LEVELS;
  vector[SDM_SPECTRAL_MAX_L] SDM_SPECTRAL_GRID;
  vector[SDM_SPECTRAL_MAX_L] SDM_SPECTRAL_GRID_COS;
  vector[SDM_SPECTRAL_MAX_L] SDM_SPECTRAL_GRID_SIN;

  SDM_SPECTRAL_LEVELS[1] = 32;
  SDM_SPECTRAL_LEVELS[2] = 64;
  SDM_SPECTRAL_LEVELS[3] = 128;
  SDM_SPECTRAL_LEVELS[4] = 256;
  SDM_SPECTRAL_LEVELS[5] = 512;

  for (m in 1:SDM_SPECTRAL_MAX_L) {
    SDM_SPECTRAL_GRID[m] = -pi() + (m - 1) * (2 * pi() / SDM_SPECTRAL_MAX_L);
    SDM_SPECTRAL_GRID_COS[m] = cos(SDM_SPECTRAL_GRID[m]);
    SDM_SPECTRAL_GRID_SIN[m] = sin(SDM_SPECTRAL_GRID[m]);
  }
