#' @title Generic S3 method for creating an initial values function
#'
#' @description Called by bmm() to create an initfun for models that require
#'   initial values to properly start sampling
#'
#' @param model The `bmmodel` object for with an initfun should be created
#' @param data The user supplied data.frame used to fit the model
#' @param formula The `brmsformula` generated by `configure_model` including the
#'   family for the `bmmodel` to be estimated.
#'
#' @return An initfun that takes no arguments except for the chain id and generates
#'   inital values suitable for the STAN parameters generated by the respective
#'   model call
#'
#' @export
#' @keywords internal developer
create_initfun <- function(model, data, formula) {
  UseMethod("create_initfun")
}

#' @export
create_initfun.bmmodel <- function(model, data, formula) {
  # skip to default method if model object contains no init_ranges
  if (is.null(model$init_ranges)) {
    NextMethod("create_initfun")
  }

  # extract information from STAN code
  standata_list <- standata(formula, data, formula$family)
  stancode_list <- stancode(formula, data, formula$family)

  stanpars_list <- extract_parameter_dimensions(
    extract_stan_blocks(stancode_list, "parameters")$parameters
  )

  # create initfun based on generated information
  my_initfun <- function(chain_id = 1) {
    # force evaluation of required information
    force(stanpars_list)
    force(standata_list)
    force(model)
    force(formula)
    force(data)

    formula_bterms <- brms::brmsterms(formula)

    # extract parameter names from model object
    parameters <- paste0(names(model$parameters))
    init_ranges <- model$init_ranges

    # add logic for non-linear formulas to extract parameters or throw error
    links <- model$links

    # initialize list of inits
    inits <- list()

    for(i in 1:length(stanpars_list)) {
      parameter <- parameters[unlist(lapply(paste0("_",parameters), grepl, x = names(stanpars_list[i])))]
      # account for covariance matrices and z-values for random effects over groups
      if (length(parameter) == 0) {
        parameter <- unlist(strsplit(names(stanpars_list[i]),"_"))[1]
      }
      parameter <- ifelse(parameter == "Intercept", "mu", parameter)
      dims <- stanpars_list[[i]][["dims"]]
      type <- stanpars_list[[i]][["type"]]
      init_name <- names(stanpars_list[i])

      if (type == "matrix") {
        inits[[eval(init_name)]] <- matrix(
          data = runif(standata_list[[dims[1]]] * standata_list[[dims[2]]], min = -.5, max = .5),
          nrow = standata_list[[dims[1]]], ncol = standata_list[[dims[2]]]
        )
      } else if(type == "array") {
        inits[[eval(init_name)]] <- array(
          data = runif(standata_list[[dims[1]]] * standata_list[[dims[2]]], min = -.5, max = .5),
          dim = standata_list[[dims[1]]]
        )
      } else if (type %in% c("cholesky_factor_corr","cholesky_factor_cov","cov_matrix","corr_matrix")) {
        inits[[eval(init_name)]] <- diag(1, standata_list[[dims]])
      } else if (type == "vector") {
        if(grepl("b_",init_name)) {
          if(has_intercept(formula_bterms$dpars[[parameter]]$fe)) {
            inits[[eval(init_name)]] <- runif(standata_list[[dims]], min = -0.1, max = 0.1)
          } else {
            term_labels <- attr(terms(formula_bterms$dpars[[parameter]]$fe), "term.labels")
            if(length(term_labels) == 1) {
              inits[[eval(init_name)]] <- link_transform(
                runif(standata_list[[dims]], min = init_ranges[[parameter]][1], max = init_ranges[[parameter]][2]),
                links[[paraneter]])
            } else {
              if(grepl(term_labels[1],":")) {
                first_term_variables <- unlist(strsplit(term_labels[1],":"))
                first_term_n_levels <- count_term_levels(data, first_term_variables)
                inits[[eval(init_name)]] <- c(
                  link_transform(runif(first_term_n_levels$total_coeffs, min = init_ranges[[parameter]][1], max = init_ranges[[parameter]][2]), links[[parameter]]),
                  runif(standata_list[[dims]] - first_term_n_levels$total_coeffs, min = -0.1, max = 0.1)
                )
              } else {
                first_term_n_levels <- count_term_levels(data, term_labels[1])
                inits[[eval(init_name)]] <- c(
                  link_transform(runif(first_term_n_levels$total_coeffs, min = init_ranges[[parameter]][1], max = init_ranges[[parameter]][2]), links[[parameter]]),
                  runif(standata_list[[dims]] - first_term_n_levels$total_coeffs, min = -0.1, max = 0.1)
                )
              }
            }
          }
          next
        }

        if(grepl("sd_",init_name)) {
          inits[[eval(init_name)]] <- runif(standata_list[[dims]], min = 0.05, max = 0.1)
          next
        }

        stop2("Initial values for vectors are only specified for b-coefficients and sd-parameters")
      } else if (type == "real") { # these will usually be Intercetps
        inits[[eval(init_name)]] <- link_transform(
          runif(1, min = init_ranges[[parameter]][1], max = init_ranges[[parameter]][2]),
          links[[parameter]])
      }
    }
    # return inits
    inits
  }

  my_initfun
}

#' @export
create_initfun.default <- function(model, data, formula) {
  inits <- 1
  return(inits)
}

# Count "levels" per term, with configurable handling for numeric columns.
count_term_levels <- function(data, vars,
                              numeric_strategy = c("one", "unique", "bins"),
                              nbins = NULL,
                              na.rm = TRUE) {
  numeric_strategy <- match.arg(numeric_strategy)

  cols <- data[vars]

  term_sizes <- vapply(cols, function(x) {
    # factors (including ordered): use declared levels
    if (is.factor(x)) return(nlevels(x))

    # characters: treat like categorical (distinct strings)
    if (is.character(x)) {
      ux <- if (na.rm) unique(na.omit(x)) else unique(x)
      return(length(ux))
    }

    # logical: usually at most 2 (TRUE/FALSE), but count distinct to be safe
    if (is.logical(x)) {
      ux <- if (na.rm) unique(na.omit(x)) else unique(x)
      return(length(ux))
    }

    # numeric/integer
    if (is.numeric(x)) {
      if (numeric_strategy == "one") {
        return(1L)  # treat continuous predictor as 1 level
      } else if (numeric_strategy == "unique") {
        ux <- if (na.rm) unique(na.omit(x)) else unique(x)
        return(length(ux))
      } else { # "bins"
        if (is.null(nbins) || nbins < 1) stop("Provide a positive 'nbins' for numeric_strategy='bins'.")
        x2 <- if (na.rm) x[!is.na(x)] else x
        if (!length(x2)) return(0L)
        b <- cut(x2, breaks = nbins, include.lowest = TRUE, right = TRUE)
        return(nlevels(b))
      }
    }

    # fallback: distinct count
    ux <- if (na.rm) unique(na.omit(x)) else unique(x)
    length(ux)
  }, integer(1L))

  list(
    per_term = term_sizes,
    total_coeffs = prod(term_sizes)
  )
}
