#' @title Generic S3 method for creating an initial values function
#'
#' @description Called by bmm() to create an initfun for models that require
#'   initial values to properly start sampling
#'
#' @param model The `bmmodel` object for with an initfun should be created
#' @param data The user supplied data.frame used to fit the model
#' @param formula The `brmsformula` generated by `configure_model` including the
#'   family for the `bmmodel` to be estimated.
#' @param prior The `brmsprior` the model will be fitted with. Parameters it
#'   holds constant are absent from the Stan code and get no initial value.
#' @param ... The arguments of [brms::brm()] besides formula, data and prior
#'   that change the Stan data or code (`data2`, `knots`,
#'   `drop_unused_levels`), passed on to [brms::standata()] and
#'   [brms::stancode()].
#'
#' @return An initfun with no arguments that generates
#'   inital values suitable for the STAN parameters generated by the respective
#'   model call
#'
#' @export
#' @keywords internal developer
create_initfun <- function(model, data, formula, prior = NULL, ...) {
  UseMethod("create_initfun")
}

# Every Stan parameter gets a value: random-effects parameters a tight start
# (small sd, z near zero, identity correlations), population-level parameters a
# draw from the model's init_ranges through the link, and everything else what
# brm(init = 1) would draw. A partial list would make cmdstanr fill the gaps at
# radius 2 and say so
#' @export
create_initfun.default <- function(model, data, formula, prior = NULL, ...) {
  standata_list <- standata(formula, data, formula$family, prior = prior, ...)
  stan_code <- stancode(formula, data, formula$family, prior = prior, ...)
  stanpars_list <- extract_parameter_dimensions(extract_stan_blocks(stan_code)$parameters)

  function() {
    force(stanpars_list)
    force(standata_list)
    force(model)

    stan_names <- names(stanpars_list)
    inits <- lapply(stan_names, function(spar) {
      spec <- stanpars_list[[spar]]
      dim <- resolve_stan_dim(spec$dims, standata_list)
      if (anyNA(dim)) {
        return(NULL)
      }
      init_ranef_param(spar, spec$types, dim) %||%
        init_fixef_param(spar, spec$types, dim, model, standata_list) %||%
        init_default_param(spec, dim, standata_list)
    })
    names(inits) <- stan_names
    inits[!vapply(inits, is.null, logical(1))]
  }
}


match_stan_to_model_par <- function(spar, model_pars) {
  # brms leaves the intercept and coefficients of the main dpar unsuffixed
  if (spar %in% c("Intercept", "b")) {
    return("mu")
  }
  parameter <- model_pars[unlist(lapply(
    paste0("(^|_)", model_pars, "(_|$)"), grepl, x = spar
  ))]
  if (length(parameter) > 1) {
    parameter <- parameter[which.max(nchar(parameter))]
  }
  if (length(parameter) == 0) {
    parameter <- strsplit(spar, "_")[[1]][1]
  }
  parameter
}


# Helper functions for initializing different parameter types ----------------

# brms names the random-effects parameters by their role, not by the model
# parameter; a constant on one coefficient makes brms replace a vector by
# per-coefficient scalars named par_<vector>_<index>
init_ranef_param <- function(spar, types, dim) {
  if (any(types %in% c("cholesky_factor_corr", "cholesky_factor_cov", "cov_matrix", "corr_matrix"))) {
    return(init_identity(types, dim))
  }
  if (grepl("^(par_)?sd_", spar)) {
    return(init_array(runif(prod(dim), min = 0.05, max = 0.1), types, dim))
  }
  if (grepl("^z_", spar)) {
    return(init_array(runif(prod(dim), min = -0.5, max = 0.5), types, dim))
  }
  NULL
}

# A matrix declaration names its size once; gr(by = ) declares an array of
# them, one per level of the by variable
init_identity <- function(types, dim) {
  identity <- diag(nrow = dim[length(dim)])
  if (!"array" %in% types) {
    return(identity)
  }
  levels <- dim[-length(dim)]
  array(rep(identity, each = prod(levels)), dim = c(levels, dim(identity)))
}

# brms names the coefficients of a parameter b_<par> (b for the main dpar) and
# replaces them by per-coefficient scalars par_b_<par>_<index> when a constant
# holds some of them fixed; a scalar gets the value its position in the vector
# would get
init_fixef_param <- function(spar, types, dim, model, standata_list) {
  index <- if (grepl("^par_b_", spar)) as.integer(sub(".*_", "", spar))
  stan_par <- if (is.null(index)) spar else sub("^par_(.*)_[0-9]+$", "\\1", spar)
  parameter <- match_stan_to_model_par(stan_par, names(model$parameters))
  init_range <- model$init_ranges[[parameter]]
  if (is.null(init_range)) {
    return(NULL)
  }
  link <- init_link(model$links[[parameter]])
  from_range <- function(n) link_transform(runif(n, min = init_range[1], max = init_range[2]), link)
  if (startsWith(stan_par, "Intercept")) {
    return(from_range(1))
  }
  if (!grepl("^b(_|$)", stan_par)) {
    return(NULL)
  }
  X <- standata_list[[sub("^b", "X", stan_par)]]
  if (is.null(X)) {
    return(NULL)
  }

  in_range <- range_coefficients(X, centered = !is.null(standata_list[[sub("^b", "Kc", stan_par)]]))
  values <- runif(length(in_range), min = -0.1, max = 0.1)
  values[in_range] <- from_range(sum(in_range))
  init_array(if (is.null(index)) values else values[index], types, dim)
}

# The coefficients that start from the model's range rather than near zero: the
# intercept, which brms folds into the first coefficient of a non-linear
# parameter, or else the columns of the first term, which are the cell means of
# a no-intercept formula. Counting them on brms's own design matrix covers
# function calls, interactions and dropped levels alike. brms centres an
# intercept, whether a parameter of its own or a constant, and drops its column
# from b, recording that as Kc_<par>; every coefficient left is then an effect.
# A 0 + Intercept design matrix carries no assign attribute
range_coefficients <- function(X, centered) {
  assign <- attr(X, "assign") %||% seq_len(ncol(X))
  if (centered) {
    return(rep(FALSE, length(assign) - 1))
  }
  assign == assign[1]
}

# init_ranges of softmax parameters are declared on the sampling scale, as
# a softmax weight has no native value of its own
init_link <- function(link) {
  if (identical(link, "softmax")) "identity" else link
}

# Stan draws initial values uniformly on the unconstrained scale and maps them
# through the parameter's declared bounds; with a radius of 1 this is exactly
# what brm(init = 1) does. Returns NULL for the types whose transform is not
# reimplemented here (simplex, ordered, ...) and for bounds that cannot be
# resolved to a number, leaving those parameters to the sampler
init_default_param <- function(spec, dim, standata_list) {
  if (!spec$type %in% c("real", "vector", "row_vector", "matrix")) {
    return(NULL)
  }
  lower <- resolve_stan_bound(spec$bounds$lower, standata_list, -Inf)
  upper <- resolve_stan_bound(spec$bounds$upper, standata_list, Inf)
  if (is.na(lower) || is.na(upper)) {
    return(NULL)
  }

  raw <- runif(prod(dim), min = -1, max = 1)
  value <- if (is.infinite(lower) && is.infinite(upper)) {
    raw
  } else if (is.infinite(upper)) {
    lower + exp(raw)
  } else if (is.infinite(lower)) {
    upper - exp(raw)
  } else {
    lower + (upper - lower) * plogis(raw)
  }
  init_array(value, spec$types, dim)
}

# rstan reads a bare length-1 numeric as a scalar and stops with "no more
# scalars to read" at a size-1 vector; cmdstanr repairs the list, rstan does
# not. The parser gives a real the dimension 1, which an array of reals drops
init_array <- function(values, types, dim) {
  if (identical(types, "real")) {
    return(values)
  }
  array(values, dim = if ("real" %in% types) dim[-length(dim)] else dim)
}

# Stan declarations carry their dimensions either as a literal (scalars) or as
# the name of a variable in the data block
resolve_stan_dim <- function(dims, standata_list) {
  vapply(dims, function(d) {
    literal <- suppressWarnings(as.numeric(d))
    if (is.na(literal)) as.numeric(standata_list[[d]])[1] else literal
  }, numeric(1), USE.NAMES = FALSE)
}

# Bounds are parsed as strings and may be numbers or the names of data
# variables; NA marks a bound that is neither
resolve_stan_bound <- function(value, standata_list, default) {
  if (is.null(value)) {
    return(default)
  }
  number <- suppressWarnings(as.numeric(value))
  if (!is.na(number)) {
    return(number)
  }
  from_data <- standata_list[[value]]
  if (is.numeric(from_data) && length(from_data) == 1) from_data else NA_real_
}
